### ISSUE TITLE
isJoined is only returning false even if the user has indeed joined the group.

### ISSUE THREAD

**Issue by mayur-bhandari** [cometchat-pro/rest-api#10]
While fetching the group information using the getGroup() method in JavaScript SDK, the isJoined parameter is returning false.
The api is not returning isJoined parameter in the response of https://kohoutek.cometchat.com/v1.8/groups/{{guid}}

**Comment by ketanyekale** [comment]
This has been fixed.

**Comment by ketanyekale** [comment]
@mayur-bhandari Please check and close the issue.

**Comment by jamesctucker** [comment]
Looks like it is working on my end. Thanks for the quick response.

**Comment by mayur-bhandari** [comment]
Closing the issue since this has been resolved.
