### ISSUE TITLE
Conversation List returns hasBlockedMe and blockedByMe as false even if i have blocked that user or that user has blocked me.

### ISSUE THREAD

**Issue by mayur-bhandari** [cometchat-pro/rest-api#15]
https://forum.cometchat.com/t/hasblockedme-and-blockedbyme-is-always-false-on-recent-conversation-list-ionic/604

**Comment by ketanyekale** [comment]
The keys `hasBlockedMe` and `hasBlockedByMe` are redundant in conversation list and will be removed.

**Comment by ketanyekale** [comment]
The API does not return these keys.

These are the default values set for the User objects in SDKs.
