### ISSUE TITLE
Not able to fetch system messages in a group.

### ISSUE THREAD

**Issue by mayur-bhandari** [cometchat-pro/rest-api#16]
As mentioned in [this](https://forum.cometchat.com/t/wrong-unread-message-count-for-group-messages/983/16) forum issue, the member of a group cannot fetch system messages in that particular group. 

Also, after following the steps as mentioned by the client we could not reproduce the issue at our end but have successfully detected the issue on his app and in a particular group.

**Comment by ketanyekale** [comment]
Thank you for reporting the issue.

The issue appears when group creation and adding members to group happens within a second. 

This has been fixed and will be forwarded to QA in a few hours.

**Comment by ketanyekale** [comment]
This has been forwarded to QA.

**Comment by ketanyekale** [comment]
This has been fixed and made live.
