### ISSUE TITLE
Incorrect format for call metadata

### ISSUE THREAD

**Issue by darshanbhanushali** [cometchat-pro/rest-api#17]
When the metadata is set in call object it returns a string instead of JSONObject in response. which throws the exception cannot convert String to JSON Object as SDK end.

**Comment by sivaramadurai** [comment]
The issue has been moved from development to testing phase. It will be released on 17th May as we follow a standard release cycle.

**Comment by ketanyekale** [comment]
The fix has been deployed to both EU and US regions.
