### ISSUE TITLE
hasJoined parameter is not received in response of AddMemberToGroup

### ISSUE THREAD

**Issue by jeetkapadia** [cometchat-pro/rest-api#6]
**Describe the bug**
hasJoined parameter is not received in response of AddMemberToGroup

**To Reproduce**
Create a group from userA and add another user to the group.

**Expected behavior**
In the group object, the hasJoined parameter must be received and value should be true.

**Actual behavior**
In the group object, the hasJoined parameter is missing.

**Screenshots** (optional)

**Enviorment/Platfrom (please complete the following information):**
 - iOS Version[ e.g iOS 12.1 ]
 - CometChat SDK Version[ e.g. 1.8.5]

**Files (Optional)**
 - `podfile` 

**Logs (Error Logs)**
fromJson for group Optional(["guid": test20, "owner": superhero2, "createdAt": 1565177913, "name": test20, "type": public, "scope": admin, "joinedAt": 1565177913])

**Additional context**

**Comment by ketanyekale** [comment]
This has been fixed.
