### ISSUE TITLE
Issue with push Notification.

### ISSUE THREAD

**Issue by ketanyekale** [cometchat-pro/rest-api#7]
The message `Let's` appears as `Letu2019s` in push notification payload.

From client on slack: https://cometchat.slack.com/archives/CFT21KASW/p1565375810143900

**Comment by sivaramadurai** [comment]
We have checked it at API end, android and iOS. The push notification is appearing as unicode symbol perfectly. I’ve attached screenshots from iOS device.


![Image from iOS](https://user-images.githubusercontent.com/48080231/62870296-0ec2a900-bd37-11e9-89be-3a276e0f51ae.png)
![IMG_2613](https://user-images.githubusercontent.com/48080231/62870315-197d3e00-bd37-11e9-8e4c-a3fc90d6b717.png)
