### ISSUE TITLE
problem creating group.

### ISSUE THREAD

**Issue by ajaygajra** [cometchat-pro/rest-api#8]
1. while creating group API response says group already exists. but there is no such group is created ever

**Comment by minisemi** [comment]
I was the one reporting the problem. I have a problem creating rooms. Any ideas why? Not sure what the error means? I get `code: "ERR_WS_INIT_FAILED", message: "Web socket process failed."`

```
wp_remote_post( "https://api-eu.cometchat.io/v2.0/groups",
            array(
                'method' => 'POST',
                'headers' => [
                    'Content-Type' => "application/json",
                    'accept' => "application/json",
                    'apikey' => $my_api_key,
                    'appid' => $my_app_id,
                ],
                'body' => json_encode(array(
                    'guid' => "30854925363137",
                    'name' => "asd",
                    'type' => 'private',
                ))
            ,
                'timeout' => 45
            )
        );
```

This code never had a problem before. All i changed with it was the url to the new API version 2.0, from 1.8.

Here's the debug response.

> "Client error: `POST https://ws-eu.cometchat.io:9091/plugins/restapi/v1/chatrooms?servicename=90795626a2cc47` resulted in a `409 Conflict` response:
> {"resource":"[90795626a2cc47]30854925363139","message":"Could not create the channel","exception":"AlreadyExistsExceptio (truncated...)
> "

It says GUID 30854925363139 already exists for my App, but it doesn't. The only group I have is the Comic Heros' Hangout

**Comment by ketanyekale** [comment]
@minisemi Can you please try to create a group again?

**Comment by minisemi** [comment]
@ketanyekale I just tried it again and I'm still getting the same error.

**Comment by minisemi** [comment]
@ketanyekale any update on this? I get the same error through your API docs test section:

![Screenshot 2019-10-03 at 10 15 55](https://user-images.githubusercontent.com/4705200/66110388-f6e50400-e5c6-11e9-86ba-730fb86c7b65.png)

**Comment by ketanyekale** [comment]
@minisemi, Please try now and let us know.

**Comment by minisemi** [comment]
@ketanyekale It works now, thank you very much!
